### ISSUE TITLE
Error on presenceUpdate.

### ISSUE THREAD

**Issue by Emdix** [Emdix/MonikaBot#8]
C:\Users\Marc\WebstormProjects\MonikaBot\events\presenceUpdate.js:8
    if(newMember.presence.activity.name === 'League of Legends') {
                                   ^

TypeError: Cannot read property 'name' of null
    at Object.exports.run (C:\Users\Marc\WebstormProjects\MonikaBot\events\presenceUpdate.js:8:36)
    at Client.client.on.args (C:\Users\Marc\WebstormProjects\MonikaBot\handler\discordEventHandler.js:11:61)
    at Client.emit (events.js:160:13)
    at PresenceUpdateHandler.handle (C:\Users\Marc\WebstormProjects\MonikaBot\node_modules\discord.js\src\client\websocket\packets\handlers\PresenceUpdate.js:46:16)
    at WebSocketPacketManager.handle (C:\Users\Marc\WebstormProjects\MonikaBot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\Users\Marc\WebstormProjects\MonikaBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:316:35)
    at WebSocketConnection.onMessage (C:\Users\Marc\WebstormProjects\MonikaBot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:279:10)
    at WebSocket.onMessage (C:\Users\Marc\WebstormProjects\MonikaBot\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:160:13)
    at Receiver._receiver.onmessage (C:\Users\Marc\WebstormProjects\MonikaBot\node_modules\ws\lib\websocket.js:145:47)

**Comment by Emdix** [comment]
Haven't observed this issue in the latest experimental. I'll close it for now. If it is still an issue I can re-open it.
