### ISSUE TITLE
No response on prune command

### ISSUE THREAD

**Issue by Zelle97** [Emdix/MonikaBot#9]
Some weird stuff going on with the prune command if the User and/or the Bot doesent have the needed Permissions.

**Example**: The User doesent have the needed Permissions. Nothing is cleared but the Bot doesent respond with a Message to tell the User that. Maybe an enhancement.

**Example:** If the Bot has permission to delete his own messages but not from others:
Deletes his messages + error in log on other messages: 

`DiscordAPIError: Missing Permissions
    at item.request.gen.end (C:\Data\Projekte\JS-Projects\MonikaBot\node_modules\discord.js\src\rest\handlers\RequestHandler.js:79:65)
    at then (C:\Data\Projekte\JS-Projects\MonikaBot\node_modules\snekfetch\src\index.js:215:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Comment by Emdix** [comment]
Should be fixed now. Just reopen the issue if there are more bugs with the same effect.
